services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    container_name: tt-nginx
    volumes:
      - ./assets:/app/assets:rw
    ports:
      - '8080:80'
    extra_hosts:    
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
