services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file: .env

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://testuser:qwerty@db/testdb
      - STATIC_HOST=client
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - '5500:5500'
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
