services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    env_file: .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  monolith:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - '8080:80'
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://testuser:qwerty@db/testdb
    depends_on:
      - db

volumes:
  postgres_data:
