services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  monolith:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        - VITE_API_HOST=http://localhost:8080
    container_name: tt-monolith
    ports:
      - '8080:80'
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://testuser:qwerty@db/testdb
      - VITE_API_HOST=http://localhost:80
    volumes:
      - ./logs:/var/log/nginx:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

volumes:
  postgres_data:
