FROM postgres:14-alpine

COPY ./infra/init-scripts/init.sh /docker-entrypoint-initdb.d/
RUN chmod a+r+x /docker-entrypoint-initdb.d/*
RUN sed -i 's/\r$//' /docker-entrypoint-initdb.d/*

COPY ./infra/init-scripts/ /init_data/
RUN chmod a+r /init_data/*
RUN sed -i 's/\r$//' /init_data/*